name: bnn
channels:
  - pytorch
  # - conda-forge
  # - defaults
dependencies:
  - python=3.7 #PyTorch and Ray do not support Python3.8
  - numpy
  - pandas
  - pip
  - setuptools
  # - cudatoolkit=10.1  # Make sure this matches the currently installed cuda version, e.g. via nvidia-smi
  # - pytorch=1.6 # For some reason just installing "pytorch" defaults to 1.4 instead of 1.6, so we pin it here.
  # - torchvision
  - pip:
    - streamlit
    - pylint # For VSCode 
    - tqdm
    - ray
    - scikit-image
    # For some reason it seems more stable to install torch via pip into this conda environment
    # If we use the above code, we sometimes (?!) end up with cuda 10.2 instead of 10.1?!
    # - torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
    - scikit-learn
    - scipy
    - cloudpickle
    # - -e file:./submodules/experiment_runner/
    # - -e file:./submodules/deep_ensembles_v2/
    
    
